name: Build CI

on:
  push:
    branches:
      - 'build/v**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/heads/build/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: node ci-build.mjs

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          draft: true
          prerelease: true
          files: |
            build/linux64/node-nim-linux64.zip
            build/win32/node-nim-win32.zip
            build/win64/node-nim-win64.zip
            build/mac/node-nim-mac.zip
            build/mac-arm/node-nim-mac-arm.zip